### ISSUE TITLE
Suggestion - Support render thumbnail for collection assets

### ISSUE THREAD

**Issue by Wolfgang-IX** [gruntworks/render_asset_thumbnails#1]
Hi i've tested on object assets it works wonderfully, but when i tried to render thumbnail for collections asset it got skipped.
tested on Blender 3.6.2, Windows 10
![image](https://github.com/gruntworks/render_asset_thumbnails/assets/47208316/6bf7f7a3-47c5-4de0-8c1a-dbca11243bab)

**Comment by gruntworks** [comment]
Hi, thanks for suggestion. Honestly I did not know that you can use collections as assets so I learned something new.
I quickly added few changes on a separate [branch](https://github.com/gruntworks/render_asset_thumbnails/tree/collection-as-asset)
Download script and reinstall if you want to check it out... 😄

**Comment by Wolfgang-IX** [comment]
thank you for quickly adding it, i could render collection thumbnail now 😁 
but there's some limitation currently, that is it won't render objects in nested collections

https://github.com/gruntworks/render_asset_thumbnails/assets/47208316/02f50a41-7446-4d87-8b29-035616e526ec

**Comment by gruntworks** [comment]
Sweet, thanks for video. Script is updated and it should select all objects in sub collections now😄

**Comment by Wolfgang-IX** [comment]
if i may add is to enable render on all object and collection before rendering each assets thumbnail, there may be a case when some object/collection render is disabled like on 00:32.

Uploading 2023-09-09 01-31-12.mp4…


other than that works great, thank you ❤

https://github.com/gruntworks/render_asset_thumbnails/assets/47208316/a6c2695d-52f0-467e-a3d0-852b5eb3b790

**Comment by gruntworks** [comment]
Oh, had the line for enabling render at the wrong place... Thanks for that, fix is on main branch 😄
